# ============= ATTACKER SCRIPTS ===============
# generates the attacker's public and private key
attacker-keygen:
	python gen-attacker-key.py

# the attacker decrypts your key with his private key and sends it back to you
attacker-decrypt:
	python decrypt-sym-key.py
